version: "3.7"

# services:
#   app:
#     build: .
#     container_name: apievent
#     restart: always
#     ports:
#       - 3333:3333
#     volumes:
#       - .:/usr/app/

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: apievent
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app/
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
